In [1]:
import numpy as np
import numpy.random as npr

In [2]:
a = np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print(a.shape)

(3, 5)


In [4]:
print(a.ndim)

2


In [5]:
print(a.dtype)

int32


In [6]:
print(a.itemsize)

4


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
print(a.size)

15


In [9]:
a = np.array([2,3,4])

In [10]:
print(a)

[2 3 4]


In [11]:
print(a.dtype)

int32


In [12]:
b = np.array([1.2,3.5,5.1])
print(b.dtype)

float64


In [14]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [15]:
c = np.array([[1,2],[3,4]], dtype = complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [16]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
print(np.ones((2,3,4), dtype=np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [18]:
print(np.empty((2,3)))

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [19]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
print(np.ones((2,3,4), dtype=np.int16))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [21]:
print(np.empty((2,3)))

[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [23]:
print(np.arange(10,30,5))

[10 15 20 25]


In [25]:
print(np.arange(0, 2, 0.3))

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [27]:
x = np.linspace(0, 99,100)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [34]:
x= np.linspace(1, 50, 25)
print(x)

[ 1.          3.04166667  5.08333333  7.125       9.16666667 11.20833333
 13.25       15.29166667 17.33333333 19.375      21.41666667 23.45833333
 25.5        27.54166667 29.58333333 31.625      33.66666667 35.70833333
 37.75       39.79166667 41.83333333 43.875      45.91666667 47.95833333
 50.        ]


In [40]:
a = np.arange(6)
print(a)
print()

b=np.arange(12).reshape(4,3)
print(b)
print()
c  = np.arange(24).reshape(2,3,4)
print(c)

[0 1 2 3 4 5]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [41]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [45]:
c = np.arange(100).reshape(2,5,10)
print(c)


[[[ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]]

 [[50 51 52 53 54 55 56 57 58 59]
  [60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [80 81 82 83 84 85 86 87 88 89]
  [90 91 92 93 94 95 96 97 98 99]]]


In [46]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)

[0 1 2 3]


In [47]:
c = a-b
print(c)

[20 29 38 47]


In [48]:
print(b**2)

[0 1 4 9]


In [49]:
print(10*np.sin(a))

[ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [50]:
print(a<35)

[ True  True False False]


In [55]:
b = np.arange(24)
print(b)

c= b.reshape(2,3,4)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [57]:
A = np.array( [[1,1], [0,1]])
B = np.array( [[2,0], [3,4]])
print(A * B)
print()
print(A @ B)
print()
print(A.dot(B))

[[2 0]
 [0 4]]

[[5 4]
 [3 4]]

[[5 4]
 [3 4]]
